### ISSUE TITLE
Content cache (view cache) is not getting cleared

### ISSUE THREAD

**Issue by pkamps** [netgen/ibexa-legacy-bridge#5]
Hi,

is there a good reason why content cache is not getting cleared?

https://github.com/netgen/ibexa-legacy-bridge/blob/5aaf2a223336f7b13d2af097e5f32f02be0149f5/bundle/Cache/LegacyCachePurger.php#L75

If not, I'd create a pull request to include it.

**Comment by emodric** [comment]
@pkamps You should ask original eZ developers on why it's not included, I don't believe I modified anything like this from the original code.

I don't see any reason why content cache should not be included, I guess, you can create the PR.

And sorry for ONLY NOW seeing this, apparently, I haven't had any notifications turned on for this repo!

**Comment by emodric** [comment]
Released the fix in 3.0.4. Thanks @pkamps !
